version: '3'

services:
  frontend:
    build: RIMA-Frontend
    image: ${IMAGE_NAME_PREFIX:-soco/}rima-frontend:${IMAGE_TAG:-latest}
    ports:
    - 8080:8080

  api:
    build: RIMA-Backend
    image: ${IMAGE_NAME_PREFIX:-soco/}rima-backend:${IMAGE_TAG:-latest}
    command: bin/web.sh
    env_file:
    - backend.env
    depends_on:
    - db
    - redis
    ports:
    - 8081:8080

  worker:
    build: RIMA-Backend
    image: ${IMAGE_NAME_PREFIX:-soco/}rima-backend:${IMAGE_TAG:-latest}
    command: bin/worker.sh
    env_file:
    - backend.env
    depends_on:
    - db
    - redis

  db:
    image: postgres
    env_file:
    - db.env
    volumes:
    - database-data:/var/lib/postgresql/data/

  redis:
    image: redis

volumes:
  database-data:
