apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  labels:
    app.kubernetes.io/component: api
    keel.sh/policy: patch
    keel.sh/match-tag: "true"
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/component: api
  template:
    metadata:
      labels:
        app.kubernetes.io/component: api
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
      - name: web
        image: inko/soco-rima-backend
        command: ['bin/api']
        ports:
        - containerPort: 8080
        startupProbe:
          httpGet:
            path: /api/accounts/data-import-status/
            port: 8080
          initialDelaySeconds: 5
          failureThreshold: 10
          periodSeconds: 5
          timeoutSeconds: 3
        readinessProbe:
          httpGet:
            path: /api/accounts/data-import-status/
            port: 8080
          periodSeconds: 15
          timeoutSeconds: 1
        livenessProbe:
          httpGet:
            path: /api/accounts/data-import-status/
            port: 8080
          periodSeconds: 60
          timeoutSeconds: 5
        env:
        - name: POSTGRES_HOST
          value: $(DB_SERVICE)
        - name: REDIS_HOST
          value: $(REDIS_SERVICE)
        - name: TEMP_DIR
          value: /tmp
        - name: GLOVE_MODEL_URL
          value: "http://$(MODEL_SERVER_SERVICE):8080/datatest_word2vec.txt"
        - name: GLOVE_MODEL_FILE_PATH
          value: /tmp/datatest_word2vec.txt
        envFrom:
        - secretRef:
            name: configuration
        resources:
          requests:
            memory: 500Mi
            cpu: 100m
          limits:
            memory: 800Mi
            cpu: 1
