apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  labels:
    app.kubernetes.io/component: worker
    keel.sh/policy: patch
    keel.sh/match-tag: "true"
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/component: worker
  template:
    metadata:
      labels:
        app.kubernetes.io/component: worker
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
      - name: worker
        image: inko/soco-rima-backend
        command: ['./bin/worker.sh']
        env:
        - name: POSTGRES_HOST
          value: $(DB_SERVICE)
        - name: REDIS_HOST
          value: $(REDIS_SERVICE)
        envFrom:
        - secretRef:
            name: configuration
        # resources:
        #   requests:
        #     memory: 110Mi
        #     cpu: 100m
        #   limits:
        #     memory: 256Mi
        #     cpu: 1
        volumeMounts:
        - name: model-cache
          mountPath: /home/app/.model_cache
      volumes:
      - name: model-cache
        persistentVolumeClaim:
          claimName: model-cache
