---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: model-cache
  labels:
    app.kubernetes.io/component: worker
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
