apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: backend-

commonLabels:
  tier: backend

resources:
- api/deployment.yaml
- api/service.yaml
- api/ingress.yaml
- redis/deployment.yaml
- redis/service.yaml
