apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../base

namespace:  sc-rima-prod
namePrefix: soco-
commonLabels:
  owner: sc
  stage: prod
  app.kubernetes.io/instance: rima-sc-prod
  app.kubernetes.io/version: master
commonAnnotations:
  contact: "Ralf Berger <ralf.berger@uni-due.de>"

secretGenerator:
- name: configuration
  env: configuration.env
images:
- name: inko/soco-rima-frontend
  newTag: "0.0.1"
- name: inko/soco-rima-backend
  newTag: "0.0.1"
- name: redis
  newTag: "6.0"
- name: postgres
  newTag: "13.2"
