name: Build RIMA-Frontend Image

on:
  push:
    tags:
    - 'v*'
    branches:
    - 'master'
    - 'dev-*'
    paths:
    - '.github/workflows/build-frontend.yml'
    - 'RIMA-Frontend'
  pull_request:
    branches:
    - 'master'

env:
  DOCKERHUB_USERNAME: socialcomputing
  IMAGE_NAME:         rima-frontend
  BUILD_CONTEXT:      ./RIMA-Frontend

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      if:   github.event_name != 'pull_request'
      uses: docker/login-action@v1
      with:
        username: ${{ env.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Get tagging metadata
      id:   meta
      uses: docker/metadata-action@v3
      with:
        images: ${{ env.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}
        tags: |
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=semver,pattern={{major}},enable=${{ !startsWith(github.ref, 'refs/tags/v0.') }}
          type=ref,event=branch
          type=ref,event=pr
          type=sha

    - name: Build and push container image
      uses: docker/build-push-action@v2
      with:
        context:    ${{ env.BUILD_CONTEXT }}
        tags:       ${{ steps.meta.outputs.tags }}
        labels:     ${{ steps.meta.outputs.labels }}
        push:       ${{ github.event_name != 'pull_request' && github.event_name != 'pull_request' }}
        cache-from: type=registry,ref=${{ env.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:buildcache
        cache-to:   type=registry,ref=${{ env.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:buildcache,mode=max
